// TODO : refactor changeInput popover code into it's own file.
// use underscore to make all methods private

$.widget( "wtw.changeEditor", {

    defaultOptions: {
        // all data generated by server side comparison goes here.
        // this is temporary mock data.
        changes:[
            // add/delete/modify.   instead of acord xpath    broker, carrier values.       ignore. don't include this.
            //                       use an id.
            {type:'modify',         uid: 937,               values: ['apple','orange'],     summary:'to-be-generated' },
            {type:'delete',         uid: 840,               values: ['Ford','Toyota'],      summary:'to-be-generated' }
            //changes.push({type:  uid: ))
            // changeEditor.trigger('refresh');
        ],

        // all view customization data goes here.
        config: {
            rejectIcon: '<i class="fa fa-circle-o"/>',
            acceptIcon: '<i class="fa fa-check-circle"/>',
            onChangeAdded:null,                 //this.defaultOnChangeAdded,  //if null, uses default callback.
            uidSelectorTemplate: '[data-change-id="${uid}"]',
            itemChangeRefAttr: 'data-change-ref',
            open: true,
            expanded:false,
            trigger: 'click',
            title:'#title',
            content:'#content',
            header: 'Changes',
            valueLabels: ['Broker', 'Carrier'],
            uidLabels:{840:'Vehicle Manufacturer?',937:'Fruit'},
        },
    },

    _create: function() {
        var options = $.extend(this.options, this.options, this.defaultOptions);
        this.element.addClass('change-editor');
        this.formatData(options);
        this.prototypeInputs(options);
        this.createPopup(this.element, options);
        this.createInputPopups(options);
    },

    // trigger events when initialized, summary dialog expanded/collapsed.  change dialog shown/hidden.

    _scrollTo: function(change) {

    },

    _createChangeSummary: function(change) {

    },

    _createChange: function(change) {

    },

    getInputIcon: function ($input) {
        // icon is assumed to be the next element in DOM.
        return $input.next();
    },

    activatePrevInput: function ($input) {
        var $inputs = this.getAllChangeInputs();
        var i = $inputs.index($input);
        var $prev = $inputs.eq( (i - 1 + $inputs.length) % $inputs.length );
        this.getInputIcon($input).popover('hide');
        this.activateInput($prev,true);
    },

    activateNextInput: function ($input) {
        var $inputs = this.getAllChangeInputs();
        var i = $inputs.index($input);
        var $next = $inputs.eq( (i + 1) % $inputs.length );
        $input.popover('hide');
        // TODO : read this attribute from config. not hard coded.
        this.activateInput($next,true);
    },

    updateChangeInputValues: function ($changeValues) {

    },

    setInputChangeValue: function (acceptIcon, $input) {
        var v = $(acceptIcon).siblings('.change-input-value').text();
        console.log('setting value ' + v);
        $input.get(0).changeValue(v);
        $(acceptIcon).parents('.change-values').find('.change-value').removeClass('accepted');
        $(acceptIcon).parents('.change-value').addClass('accepted');
    },

    updateChangeInputState: function ($popover, $input) {
        var currentValue = $input.get(0).changeValue();

        $popover.find('.change-value').each(function(i, value) {
            // TODO : make a compareChangeValue method. this may get tricky for non-string values (boolean, dates, etc...)
            if (currentValue===$(value).find('.change-input-value').text()) {
                $(this).addClass('accepted');
            }
            else {
                $(this).removeClass('accepted');
            }
        });
    },

    createInputIcon: function () {
        // make this an options value.  options.config.inputIcon = ...
        return $('<li class="fa fa-asterisk change-input-icon"></li>');
    },

    toggleInputPopup: function ($icon, $input, change) {
        var $this = this;
        // show lazily instantiated popover.
        if ($icon.data('bs.popover')) {
            $icon.popover('toggle');
            return;
        }

        // create if doesn't exist.
        $icon.popover({
            placement: 'bottom',
            trigger: 'manual',
            html : true,
            title: function() {
                var template = Handlebars.compile($('#dialogTitle').html());
                return template(change);
            },
            content: function() {
                var template = Handlebars.compile($('#dialogContent').html());
                return template(change);
            }
        })
        .data('bs.popover')
        .tip()
        .addClass('change-input-popover');
        $icon.popover('show');

        $icon.on('shown.bs.popover', function() {
            var $popover = $icon.data('bs.popover').tip();
            $this.updateChangeInputState($popover, $input);
            $popover.find('.next-change').click(function() {
                $this.activateNextInput($input);
            });
            $popover.find('.prev-change').click(function() {
                $this.activatePrevInput($input);
            });
            $popover.find('.change-input-accept').click(function() {
                $this.setInputChangeValue(this, $input);
            });
        });

    },

    createInputPopups: function (options) {
        var $this = this;
        $.each(options.changes, function(i,change) {
            var $input = $this.getChangeInput(change.uid);
            var $icon = $this.createInputIcon();
            $icon.insertAfter($input);

            $icon.click(function() {
                $this.toggleInputPopup($(this), $input, change);
            });

        });

    },

    createPopup: function (element, options) {
        var shown = this.editorShown.bind(this);
        var config = options.config;
        var title = config.title;
        var content = config.content;

        element.popover({
            placement: 'bottom',
            trigger: 'click',
            container:'body',
            html : true,
            title: function() {
                var template = Handlebars.compile($(title).html());
                return template(options);
            },
            content: function() {
                var template = Handlebars.compile($(content).html());
                return template(options);
            }
        })
            .data('bs.popover')
            .tip()
            .addClass('change-panel-popover');

        element.on('shown.bs.popover', function() {
            shown($(this), options);
        });
        element.popover('show');

        // hide any change input popovers when you click somewhere else on screen.
        $('body').on('click', function (e) {
            $('.change-input-icon').each(function () {
                //the 'is' for buttons that trigger popups
                //the 'has' for icons within a button that triggers a popup
                if (!$(this).is(e.target) && $(this).has(e.target).length === 0 && $('.popover').has(e.target).length === 0) {
                    $(this).popover('hide');
                }
            });
        });
    },

    initChangeState : function(i,change) {
        var $this = this;
        var $input = $this.getChangeInput(change.uid);
        var input = $input.get(0);
        var currentValue = $input.get(0).changeValue();
        $.each(change.values, function(idx, value) {
            // TODO : ignore case and/or whitespace?
            if (currentValue===value) {
                $this.getChangeItem(change.uid);
                $this.updateActiveValue($this.getChangeItem(change.uid), change, idx);
            }
        });
    },

    initState : function(options) {
        var initChangeState = this.initChangeState.bind(this);
        $.each(options.changes, initChangeState);
    },

    formatData : function(options) {
        var config = options.config;
        $.each(options.changes, function(i,change) {
            console.log('change'+change);
            change.summary = config.uidLabels[change.uid];
            if (!change.summary) {
                change.summary = '['+change.uid+']';
                console.log('no label was given for the change with id ' + change.uid + '  (using id as default label)');
            }
            change.formattedValues = [];
            $.each(change.values, function(i,value) {
                console.log('value'+value);
                change.formattedValues.push(
                    {   value: value,
                        label:config.valueLabels[i]
                    }
                );
            });
        });
    },

    getChangeInput : function(uid) {
        var selector = this.options.config.uidSelectorTemplate.replace('${uid}', uid);
        var $result = $(selector);
        if ($result.length==0) {
            throw 'can not find element matching "' + selector + '" when trying to view change  (there should be a form input that matches this)';
        }
        return $result;
    },

    getAllChangeInputs : function(uid) {
        var selector = this.options.config.uidSelectorTemplate.replace('="${uid}"', '');
        if ($(selector).length==0) {
            throw 'can not find any change form inputs "' + selector;
        }
        return $(selector);
    },

    getChangeItem : function(uid) {
        var selector = '['+this.options.config.itemChangeRefAttr +'="'+ uid+'"]';
        if ($(selector).length==0) {
            throw 'can not find element matching "' + selector + '" when trying to view change  (there should be a form input that matches this)';
        }
        return $(selector);
    },

    // add a generic "changeValue" function to all form inputs.
    // it is responsible for getting/setting values.
    prototypeInputs: function(options) {
        var cv = this.changeValue;
        var $this = this;
        $.each(options.changes, function(i,change) {
            var $input = $this.getChangeInput(change.uid);
            var input = $input.get(0);
            input.changeValue = cv;
        });
    },

    changeValue : function(value) {
        // TODO : refactor into method and pass function into switch.
        var $this = $(this);
        if (value) {
            console.log('setting value for ' + $this.attr('data-change-id') + ' to ' + value);
            if (this.type=='text') {
                $this.val(value);
            }
            else if (this.type='select') {
                $this.val(value);
            }
        }
        else {
            var result = '';
            if (this.type == 'text') {
                result = $this.val();
            }
            else if (this.type = 'select') {
                result = $this.val();
            }
        }
        return result;
    },

    updateActiveValue: function ($changeItem, change, index) {
        // remove all other (if any) active items, and highlight this one.
        // TODO : chain these two lines together after debugging...
        $changeItem.find('.change-value').removeClass('active');
        $changeItem.find('.change-value').eq(index).addClass('active');
    },

    setActiveChangeValue : function($action, change, index) {
        var value = change.values[index];
        var $input = this.getChangeInput(change.uid);
        $input.get(0).changeValue(value);
        this.updateActiveValue($action.parents('.change-item'),change,index);
    },

    activateInput: function ($input, showPopup) {
        if ($input.length==0) return;
        this.getAllChangeInputs().removeClass('active');
        $('html, body').animate({
            scrollTop: $input.offset().top}, 350, function() {
            $input.addClass('active');
        });
        if (showPopup) {
            this.getInputIcon($input).popover('show');
        }
    },

    viewChange : function($changeItem) {
        // select the item in the main panel
        var uid = $changeItem.attr(this.options.config.itemChangeRefAttr);
        $('.change-input').popover('hide');
        $changeItem.siblings().removeClass('active');
        $changeItem.addClass('active');
        // ..now deal with the form input itself
        this.activateInput(this.getChangeInput(uid));
    },

    defaultOnChangeAdded : function($changeItem, options, change) {
        $changeItem.attr('data-change-ref',change.uid);
        var $changeValues = $changeItem.find('.change-value');
        var viewChange = this.viewChange.bind(this);
        var setActiveChange = this.setActiveChangeValue.bind(this);

        // if you click on the *unselected* icon, it will accept the change (set its value and update status).
        $.each($changeValues, function(i, changeValue) {
            $(changeValue).find('.change-reject').click(function(e) {
                setActiveChange($(this), change, i);
            });
        });

        // if you click on item row, it will scroll the window and highlight the change in the form.
        $changeItem.click(function(e) {
            // TODO : add highlight change animation.
            viewChange($changeItem);
        });
    },

    advanceActiveChange: function ($content, delta) {
        var $items = $content.find('.change-item');
        var $active = $content.find('.change-item.active');
        var index = ($active.length!=0) ? $items.index($active)+delta : 0;
        var count = $items.length;
        index = (index<0) ? count - 1 :
                (index>=count) ? 0 :
                    index;
        $active.removeClass('active');
        this.viewChange($items.eq(index));
    },

    initPrevNextButtons: function ($popover, options) {
        var advance = this.advanceActiveChange.bind(this);
        $popover.find('.next-change').click(function() {
            advance($popover, 1);
        });
        $popover.find('.prev-change').click(function() {
            advance($popover, -1);
        });
    },

    editorShown : function($popoverTrigger, options) {
        // the trigger is the element that the popover is attached to.  we need the actual popover itself.
        var $popover = $popoverTrigger.data('bs.popover').tip();
        var callback = options.config.onChangeAdded ? options.config.onChangeAdded.bind(this) : this.defaultOnChangeAdded.bind(this);

        this.initPrevNextButtons($popover, options);

        $popover.find('.change-item').each(function(i) {
            callback($(this), options, options.changes[i]);
        });

        this.initState(options);
    }

});














